CAAR FOM Case
cholla-hydro/cholla pull request #380
Opened 2024-03-08 21:03 UTC by reubendb

Minor fixes to get CAAR FOM case to run. Also include example input files and jobscript stub.

2024-03-08 21:51 UTC, bcaddy commented on src/io/io.cpp
What's the purpose of these changes?

2024-03-08 21:54 UTC, bcaddy requested changes

2024-03-08 21:54 UTC, bcaddy commented on src/particles/io_particles.cpp
What's the purpose of moving this line out of the ifdef?

2024-03-13 23:06 UTC, brantr commented on src/particles/io_particles.cpp
I suspect @reubendb was using `TILED_INITIAL_CONDITIONS`, so `nfile` would not be defined when it's called by `Load_Particles_Data_HDF5(file_id, nfile, P); `later in the function.  I think it should actually go outside the `MPI_CHOLLA` `ifdef` into the main body of the function.

2024-03-14 00:09 UTC, brantr commented on src/io/io.cpp
On Frontier, when compiling, the following error is thrown:

```
src/io/io.cpp:2275:3: error: no matching function for call to 'sprintf'
  sprintf(filename, "%sics_%dMpc_%d.h5", P.indir, (int)P.tile_length / 1000,
  ^~~~~~~
/usr/include/stdio.h:334:12: note: candidate function not viable: no known conversion from 'std::string' (aka 'basic_string<char>') to 'char *__restrict' for 1st argument
extern int sprintf (char *__restrict __s,
           ^
```

So either something like` filename.assign()` or another char string needs to be used.

2024-03-14 00:15 UTC, brantr commented on src/particles/io_particles.cpp
Indeed, when compiling on Frontier a FOM run we get:

```
src/particles/io_particles.cpp:59:37: error: use of undeclared identifier 'nfile'
  Load_Particles_Data_HDF5(file_id, nfile, P);
                                    ^
```
I'd suggest moving the line

  const int nfile              = P->nfile;  // output step you want to read from

outside all of the ifdefs, immediately after the HDF5 check.

2024-03-14 15:00 UTC, bcaddy commented on src/io/io.cpp
In that case, I think that rather than creating a static `char` array we should just use the 'c_str()` or `data()` methods of  `std::string`. It's safer and doesn't run into the issue of having being too short.

2024-03-14 15:02 UTC, bcaddy commented on src/particles/io_particles.cpp
I agree, moving it out of the `MPI_CHOLLA` check is the right move.

2024-03-14 15:41 UTC, reubendb commented on src/io/io.cpp
`sprintf()` needs to write to a char array. Both `c_str` and `data` method just get the C string and pointer of `std::string`, respectively, and my understanding is one cannot write to them. 
Overflow is a valid concern; not sure what to do with `sprintf()` other than making larger buffer (suggestions?).

2024-03-14 15:43 UTC, reubendb commented on src/particles/io_particles.cpp
It was originally there, outside of all ifdef.  Someone moved them inside one of the ifdef. Not sure what the motivation was; I suspected possibly to avoid un-used declared variable so  I just tried to follow it.

2024-03-14 15:53 UTC, evaneschneider commented on src/particles/io_particles.cpp
Leaving it inside of the MPI ifdef seems safest if we don't know why it was moved there.

2024-03-14 15:54 UTC, evaneschneider commented on src/io/io.cpp
Given the implementation @reubendb works, I think this PR is fine as-is, and we can optimize it later in a separate PR.

2024-03-14 15:55 UTC, bcaddy approved these changes

2024-03-14 15:57 UTC, brantr commented on src/particles/io_particles.cpp
If the `nfile` definition is moved outside the MPI ifdef, I think the code will not compile without `MPI_CHOLLA` set.

2024-03-19 17:10 UTC, merged